### ISSUE TITLE
Markdown to Json converter

### ISSUE THREAD

**Issue by Proliecan** [TheGiddyLimit/5etools-utils#2]
I would love to be able to use the converter from https://5e.tools/converter.html to convert markdown statblocks into json Homebrew files in a VSCode Extension to make it very easy to convert homebrew elements into the schema used by 5e.tools ecosystem.
I cannot for the heck of me work out how to do it with the js https://5e.tools/converter.html uses.
I would love it to have a tool or some js to  use for this purpose to make homebrewing and using it with 5e.tools easier.

**Comment by revilowaldow** [comment]
Not quite what you're looking for but have you seen: 
https://marketplace.visualstudio.com/items?itemName=revilowaldow.5etools-language-server
It has a lot of insertable snippets to get you most of the way there, and has schema validation to make sure you've got correct data.

https://user-images.githubusercontent.com/52298102/204143606-e8853cc3-608b-468c-946e-e8fb1f687f25.mp4

Edit: please excuse the horrendous compression from github

**Comment by TheGiddyLimit** [comment]
Doing this "right" would involve virtually re-writing all of 5etools; doing it "wrong" would be a constant maintenance headache. It's a fine idea, but as a feature request, is more suited to a `/featurerequest` in our Discord--should the community really _really_ want it, it could happen. Otherwise, it's a big time/energy sink for what feels to me like a fringe feature
